name: build-gem
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      # Clone the source code on the runner
      - uses: actions/checkout@v3
      
      # Perform setup for Ruby 2.7
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true
      
      # Build the gem
      - run: gem build jekyll-theme-gitbook.gemspec
      
      # Publish the gem to RubyGems when a new release is tagged
      - if: startsWith(github.ref, 'refs/tags')
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem push *.gem
        env:
          GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"
